// Portfolio data — placeholder content based on reference structure.
// Replace `src` URLs once real artwork is uploaded.

const PORTFOLIO = [
  {
    id: 'food',
    num: '01',
    title: 'Food',
    titleEm: 'Illustration',
    jp: '料理イラスト',
    desc: '「見たら欲望が沸いた・・・！」と思って頂けるようなイラストを目指して描いております。今年の絵馬ナイラスト・カフェメニューなど、Vtuber様のご依頼で描かせていただきました。',
    cols: 3,
    items: [
      { id:'f1', t:'季節のお弁当（春）', jp:'季節のお弁当・春', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-haru.jpg' },
      { id:'f2', t:'季節のお弁当（夏）', jp:'季節のお弁当・夏', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-natsu.jpg' },
      { id:'f3', t:'季節のお弁当（秋）', jp:'季節のお弁当・秋', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-aki.jpg' },
      { id:'f4', t:'季節のお弁当（冬）', jp:'季節のお弁当・冬', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-huyu.jpg' },
      { id:'f5', t:'お茶',               jp:'お茶',             src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/ocha.jpg' },
      { id:'f6', t:'紅茶',               jp:'紅茶',             src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281242/tea.jpg' },
      { id:'f7', t:'アイスとお揚げ',     jp:'アイスとお揚げ',   src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281242/ice-oage.jpg' },
      { id:'f8', t:'抹茶ロール',         jp:'抹茶ロール',       src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281242/macharoll.jpg' },
    ],
  },
  {
    id: 'live2d',
    num: '02',
    title: 'Live2D',
    titleEm: 'Work',
    jp: 'Live2D ワーク',
    desc: '映像に動くことをモットーに制作しており、特に表情が活き活きしたモデルを目指しています。モデルは男性・女性問わず承っております。',
    cols: 2,
    items: [
      { id:'l1', kind:'video', t:'Original Character', jp:'オリジナルキャラクター モデリング', tone:'#3a3a48', w:1600, h:900 },
      { id:'l2', t:'Pink Hair Ref Sheet', jp:'立ち絵・パーツ分け', tone:'#f4d4dc', w:1200, h:1200 },
      { id:'l3', kind:'video', t:'Vtuber 鏡花トウヤツ', jp:'モデリング実装', tone:'#c46f7e', w:1600, h:900 },
      { id:'l4', t:'Kimono Character', jp:'立ち絵・パーツ分け', tone:'#d75a4a', w:1200, h:1200 },
      { id:'l5', kind:'video', t:'Theo Macbeth', jp:'モデル制作実況', tone:'#1a3a3a', w:1600, h:900 },
      { id:'l6', t:'Theo Macbeth Ref',  jp:'立ち絵・パーツ分け', tone:'#2a4040', w:1200, h:1200 },
      { id:'l7', kind:'video', t:'Yorufumi Project', jp:'夜想ふみ模型制作実況', tone:'#2c4a52', w:1600, h:900 },
      { id:'l8', t:'Yorufumi Ref',      jp:'立ち絵・パーツ分け', tone:'#5a8077', w:1200, h:1200 },
      { id:'l9', kind:'video', t:'Gogonosuke', jp:'午後野ご座制作実況', tone:'#d7b876', w:1600, h:900 },
      { id:'l10',t:'Gogonosuke Ref',    jp:'立ち絵・パーツ分け', tone:'#7a8867', w:1200, h:1200 },
    ],
  },
  {
    id: 'sd',
    num: '03',
    title: 'SD',
    titleEm: 'Illustration',
    jp: 'デフォルメ・LINEスタンプ',
    desc: 'ご依頼で描かせていただいたイラストや、LINEスタンプのイラストです。',
    cols: 4,
    items: [
      { id:'s1', t:'Chibi Boy — Suit',     jp:'SDキャラクター',  tone:'#dde2ec', w:600, h:900 },
      { id:'s2', t:'Chibi Girl — Casual',  jp:'SDキャラクター',  tone:'#f7e1cf', w:600, h:900 },
      { id:'s3', t:'Chibi — Hoodie',       jp:'SDキャラクター',  tone:'#cfd9c5', w:600, h:900 },
      { id:'s4', t:'French Bulldog Set',   jp:'LINEスタンプ',    tone:'#efe1c8', w:900, h:600 },
      { id:'s5', t:'Frog Sticker Pack',    jp:'LINEスタンプ',    tone:'#cee0c0', w:900, h:600 },
      { id:'s6', t:'Hamster Sticker',      jp:'LINEスタンプ',    tone:'#efe5d2', w:900, h:600 },
    ],
  },
  {
    id: 'character',
    num: '04',
    title: 'Character',
    titleEm: 'Illustration',
    jp: 'キャラクター',
    desc: 'オリジナル・依頼を含むキャラクターイラスト。立ち姿や雰囲気を大切に描いています。',
    cols: 3,
    items: [
      { id:'c1', t:'Red Coat',     jp:'ファンアート', tone:'#a83a3a', w:800, h:1000 },
      { id:'c2', t:'Snow Day',     jp:'オリジナル',   tone:'#cfd9e0', w:800, h:1000 },
      { id:'c3', t:'Summer Pier',  jp:'オリジナル',   tone:'#a8c8d4', w:800, h:1000 },
      { id:'c4', t:'Crimson Room', jp:'オリジナル',   tone:'#9e2a2a', w:800, h:1000 },
      { id:'c5', t:'Knit Sweater', jp:'オリジナル',   tone:'#c47272', w:800, h:1000 },
      { id:'c6', t:'Schoolyard',   jp:'オリジナル',   tone:'#3a3a4a', w:800, h:1000 },
      { id:'c7', t:'Cheongsam',    jp:'オリジナル',   tone:'#a83434', w:800, h:1000 },
      { id:'c8', t:'Soldier',      jp:'オリジナル',   tone:'#5a6a4a', w:800, h:1000 },
      { id:'c9', t:'Skirt & Bag',  jp:'オリジナル',   tone:'#a8a8a8', w:800, h:1000 },
    ],
  },
  {
    id: 'other',
    num: '05',
    title: 'Other',
    titleEm: 'Works',
    jp: 'ファンアート・その他',
    desc: '趣味で描いたファンアートや、コンペに応募したイラストです。UFOや写真は3DCGでモデリングしたものです。',
    cols: 3,
    items: [
      { id:'o1', t:'Halloween Witch', jp:'ファンアート', tone:'#e89a3a', w:800, h:1000 },
      { id:'o2', t:'Kiki Tribute',    jp:'ファンアート', tone:'#a04848', w:800, h:1000 },
      { id:'o3', t:'Triple Burger',   jp:'コンペ作品',   tone:'#c87648', w:800, h:1000 },
      { id:'o4', t:'Bacon Strips',    jp:'食イラスト',   tone:'#a85838', w:800, h:1000 },
      { id:'o5', t:'Chips Plate',     jp:'食イラスト',   tone:'#d8a868', w:800, h:1000 },
      { id:'o6', t:'Fruit Sundae',    jp:'食イラスト',   tone:'#e8c8b8', w:800, h:1000 },
      { id:'o7', t:'Sandwich Stack',  jp:'食イラスト',   tone:'#d8b888', w:800, h:1000 },
      { id:'o8', t:'Taiyaki',         jp:'食イラスト',   tone:'#c89868', w:800, h:1000 },
      { id:'o9', t:'Sushi Set',       jp:'食イラスト',   tone:'#e8d8c8', w:800, h:1000 },
      { id:'o10',t:'Napolitan',       jp:'食イラスト',   tone:'#d85838', w:800, h:1000 },
      { id:'o11',t:'Quiet Field',     jp:'3DCG',        tone:'#7894a4', w:800, h:1000 },
      { id:'o12',t:'Alien Portrait',  jp:'3DCG',        tone:'#9aa8a8', w:800, h:1000 },
      { id:'o13',t:'Twin Aliens',     jp:'3DCG',        tone:'#88a0a8', w:800, h:1000 },
      { id:'o14',t:'UFO Encounter',   jp:'3DCG',        tone:'#a8b4b8', w:800, h:1000 },
      { id:'o15',t:'UFO at Dusk',     jp:'3DCG',        tone:'#d8c4a8', w:800, h:1000 },
    ],
  },
];

window.PORTFOLIO = PORTFOLIO;
