// Portfolio data — placeholder content based on reference structure.
// Replace `src` URLs once real artwork is uploaded.

const PORTFOLIO = [
  {
    id: 'food',
    num: '01',
    title: 'Food',
    titleEm: 'Illustration',
    jp: '料理イラスト',
    desc: '「見たら食欲が沸いた・・・！」と思って頂けるようなイラストを目指して描いております。',
    cols: 3,
    items: [
      { id:'f0', t:'ホロライブ ラオーラ・パンテーラ様 配信用背景', jp:'料理の作画を担当しました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778363088/haishin-illust.jpg' },
      { id:'f1', t:'季節のお弁当（春）', jp:'Vtuberの三七百アメ様からのご依頼で描かせていただきました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-haru.jpg' },
      { id:'f2', t:'季節のお弁当（夏）', jp:'Vtuberの三七百アメ様からのご依頼で描かせていただきました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-natsu.jpg' },
      { id:'f3', t:'季節のお弁当（秋）', jp:'Vtuberの三七百アメ様からのご依頼で描かせていただきました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-aki.jpg' },
      { id:'f4', t:'季節のお弁当（冬）', jp:'Vtuberの三七百アメ様からのご依頼で描かせていただきました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-huyu.jpg' },
      { id:'f5', t:'お茶',               jp:'',             src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/ocha.jpg' },
      { id:'f6', t:'紅茶',               jp:'',             src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281242/tea.jpg' },
      { id:'f7', t:'アイスとお揚げ',     jp:'',   src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281242/ice-oage.jpg' },
      { id:'f8', t:'抹茶ロール',           jp:'',         src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281242/macharoll.jpg' },
      { id:'f9', t:'バレンタインイラスト', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778283791/rozemifanart.webp' },
      { id:'f10', t:'シャンパン',          jp:'',          src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778283940/champagne.webp' },
      { id:'f11', t:'カクテル',            jp:'',            src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778283939/kakuteru.webp' },
      { id:'f12', t:'カクテル2',           jp:'カクテル',            src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778283941/kakuteru2.webp' },
      { id:'f13', t:'天丼',   jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778653022/tendon_fkvxo9.jpg' },
      { id:'f14', t:'ごはん', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778653207/rice_mb700y.jpg' },
      { id:'f15', t:'サンドイッチ', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778653208/sandwich_tzpc1j.jpg' },
    ],
  },
  {
    id: 'live2d',
    num: '02',
    title: 'Live2D',
    titleEm: 'Work',
    jp: 'Live2D ワーク',
    desc: '綺麗に動くことをモットーに制作しております。',
    cols: 2,
    items: [
      { id:'l1', t:'オリジナルキャラ',   jp:'立ち絵・パーツ分け', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778284413/originalchara.jpg' },
      { id:'l2', kind:'video', t:'オリジナルキャラ',   jp:'モデリング実装', src:'https://www.youtube.com/embed/LZL5OW8XzsQ', thumb:'https://img.youtube.com/vi/LZL5OW8XzsQ/hqdefault.jpg' },
      { id:'l3', t:'種木トウテツ様',     jp:'立ち絵・パーツ分け', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778284415/toutetsusama.jpg' },
      { id:'l4', kind:'video', t:'種木トウテツ様',     jp:'モデリング実装', src:'https://www.youtube.com/embed/efBrXL5sZDc', thumb:'https://img.youtube.com/vi/efBrXL5sZDc/hqdefault.jpg' },
      { id:'l5', t:'テオ・マクベス様',   jp:'立ち絵・パーツ分け', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778284831/teosama.jpg' },
      { id:'l6', kind:'video', t:'テオ・マクベス様',   jp:'モデリング実装', src:'https://www.youtube.com/embed/dKAQOHyat_Q', thumb:'https://img.youtube.com/vi/dKAQOHyat_Q/hqdefault.jpg' },
      { id:'l7', t:'午後野ごぅ様',       jp:'立ち絵・パーツ分け', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778284414/gousama.jpg' },
      { id:'l8', kind:'video', t:'午後野ごぅ様',       jp:'モデリング実装', src:'https://www.youtube.com/embed/sIsIDSL3Jno', thumb:'https://img.youtube.com/vi/sIsIDSL3Jno/hqdefault.jpg' },
    ],
  },
  {
    id: 'sd',
    num: '03',
    title: 'SD',
    titleEm: 'Illustration',
    jp: 'デフォルメ・LINEスタンプ',
    desc: 'ご依頼で描かせていただいたイラストや、LINEスタンプのイラストです。',
    cols: 1,
    center: true,
    items: [
      { id:'s0', t:'SDイラスト', jp:'SDイラスト', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778639279/sd-illustration.avif', maxWidth:'50%' },
    ],
  },
  {
    id: 'other',
    num: '04',
    title: 'Other',
    titleEm: 'Works',
    jp: 'ファンアート・その他',
    desc: '趣味で描いたファンアートや、コンペに応募したイラストです。UFOや写真は3DCGでモデリングしたものです。',
    cols: 3,
    items: [
      { id:'o1', t:'犬',   jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778640013/dog.jpg' },
      { id:'o2', t:'猫',   jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778640014/cat.jpg' },
      { id:'o3', t:'ハンバーガー', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778640013/hamburger.jpg' },
      { id:'o4', t:'寿司', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778640013/sushi.jpg' },
      { id:'o5', t:'卵',   jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778640012/egg.jpg' },
      { id:'o6', t:'もも', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778640013/momo.jpg' },
      { id:'o7', t:'バニーエリス', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778640013/bunnyeris.jpg' },
      { id:'o8', t:'イラスト', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778640014/G6C3NfyasAElwm8_xbkjbt.jpg' },
      { id:'o9', t:'イラスト', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778653021/18_fzajkc_jm35ln.webp' },
      { id:'o10', t:'イラスト', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778653020/13_nyzroe_bgv5tn.webp' },
    ],
  },
];

window.PORTFOLIO = PORTFOLIO;
