// Portfolio data — placeholder content based on reference structure.
// Replace `src` URLs once real artwork is uploaded.

const PORTFOLIO = [
  {
    id: 'food',
    num: '01',
    title: 'Food',
    titleEm: 'Illustration',
    jp: '料理イラスト',
    desc: '「見たら食欲が沸いた・・・！」と思って頂けるようなイラストを目指して描いております。',
    cols: 3,
    items: [
      { id:'f0', t:'ホロライブ ラオーラ・パンテーラ様 配信用背景', jp:'料理の作画を担当しました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778363088/haishin-illust.jpg' },
      { id:'f1', t:'季節のお弁当（春）', jp:'Vtuberの三七百アメ様からのご依頼で描かせていただきました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-haru.jpg' },
      { id:'f2', t:'季節のお弁当（夏）', jp:'Vtuberの三七百アメ様からのご依頼で描かせていただきました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-natsu.jpg' },
      { id:'f3', t:'季節のお弁当（秋）', jp:'Vtuberの三七百アメ様からのご依頼で描かせていただきました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-aki.jpg' },
      { id:'f4', t:'季節のお弁当（冬）', jp:'Vtuberの三七百アメ様からのご依頼で描かせていただきました', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/kisetu-obentou-huyu.jpg' },
      { id:'f5', t:'お茶',               jp:'',             src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281243/ocha.jpg' },
      { id:'f6', t:'紅茶',               jp:'',             src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281242/tea.jpg' },
      { id:'f7', t:'アイスとお揚げ',     jp:'',   src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281242/ice-oage.jpg' },
      { id:'f8', t:'抹茶ロール',           jp:'',         src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778281242/macharoll.jpg' },
      { id:'f9', t:'バレンタインイラスト', jp:'', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778283791/rozemifanart.webp' },
      { id:'f10', t:'シャンパン',          jp:'',          src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778283940/champagne.webp' },
      { id:'f11', t:'カクテル',            jp:'',            src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778283939/kakuteru.webp' },
      { id:'f12', t:'カクテル2',           jp:'カクテル',            src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778283941/kakuteru2.webp' },
    ],
  },
  {
    id: 'live2d',
    num: '02',
    title: 'Live2D',
    titleEm: 'Work',
    jp: 'Live2D ワーク',
    desc: '綺麗に動くことをモットーに制作しております。',
    cols: 2,
    items: [
      { id:'l1', t:'オリジナルキャラ',   jp:'立ち絵・パーツ分け', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778284413/originalchara.jpg' },
      { id:'l2', kind:'video', t:'オリジナルキャラ',   jp:'モデリング実装', src:'https://www.youtube.com/embed/LZL5OW8XzsQ', thumb:'https://img.youtube.com/vi/LZL5OW8XzsQ/hqdefault.jpg' },
      { id:'l3', t:'種木トウテツ様',     jp:'立ち絵・パーツ分け', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778284415/toutetsusama.jpg' },
      { id:'l4', kind:'video', t:'種木トウテツ様',     jp:'モデリング実装', src:'https://www.youtube.com/embed/efBrXL5sZDc', thumb:'https://img.youtube.com/vi/efBrXL5sZDc/hqdefault.jpg' },
      { id:'l5', t:'テオ・マクベス様',   jp:'立ち絵・パーツ分け', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778284831/teosama.jpg' },
      { id:'l6', kind:'video', t:'テオ・マクベス様',   jp:'モデリング実装', src:'https://www.youtube.com/embed/dKAQOHyat_Q', thumb:'https://img.youtube.com/vi/dKAQOHyat_Q/hqdefault.jpg' },
      { id:'l7', t:'午後野ごぅ様',       jp:'立ち絵・パーツ分け', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778284414/gousama.jpg' },
      { id:'l8', kind:'video', t:'午後野ごぅ様',       jp:'モデリング実装', src:'https://www.youtube.com/embed/sIsIDSL3Jno', thumb:'https://img.youtube.com/vi/sIsIDSL3Jno/hqdefault.jpg' },
    ],
  },
  {
    id: 'sd',
    num: '03',
    title: 'SD',
    titleEm: 'Illustration',
    jp: 'デフォルメ・LINEスタンプ',
    desc: 'ご依頼で描かせていただいたイラストや、LINEスタンプのイラストです。',
    cols: 2,
    items: [
      { id:'s0', t:'SDイラスト', jp:'SDイラスト', src:'https://res.cloudinary.com/dsljwhlrb/image/upload/v1778639279/sd-illustration.avif' },
    ],
  },
  {
    id: 'character',
    num: '04',
    title: 'Character',
    titleEm: 'Illustration',
    jp: 'キャラクター',
    desc: 'オリジナル・依頼を含むキャラクターイラスト。立ち姿や雰囲気を大切に描いています。',
    cols: 3,
    items: [
      { id:'c1', t:'Red Coat',     jp:'ファンアート', tone:'#a83a3a', w:800, h:1000 },
      { id:'c2', t:'Snow Day',     jp:'オリジナル',   tone:'#cfd9e0', w:800, h:1000 },
      { id:'c3', t:'Summer Pier',  jp:'オリジナル',   tone:'#a8c8d4', w:800, h:1000 },
      { id:'c4', t:'Crimson Room', jp:'オリジナル',   tone:'#9e2a2a', w:800, h:1000 },
      { id:'c5', t:'Knit Sweater', jp:'オリジナル',   tone:'#c47272', w:800, h:1000 },
      { id:'c6', t:'Schoolyard',   jp:'オリジナル',   tone:'#3a3a4a', w:800, h:1000 },
      { id:'c7', t:'Cheongsam',    jp:'オリジナル',   tone:'#a83434', w:800, h:1000 },
      { id:'c8', t:'Soldier',      jp:'オリジナル',   tone:'#5a6a4a', w:800, h:1000 },
      { id:'c9', t:'Skirt & Bag',  jp:'オリジナル',   tone:'#a8a8a8', w:800, h:1000 },
    ],
  },
  {
    id: 'other',
    num: '05',
    title: 'Other',
    titleEm: 'Works',
    jp: 'ファンアート・その他',
    desc: '趣味で描いたファンアートや、コンペに応募したイラストです。UFOや写真は3DCGでモデリングしたものです。',
    cols: 3,
    items: [
      { id:'o1', t:'Halloween Witch', jp:'ファンアート', tone:'#e89a3a', w:800, h:1000 },
      { id:'o2', t:'Kiki Tribute',    jp:'ファンアート', tone:'#a04848', w:800, h:1000 },
      { id:'o3', t:'Triple Burger',   jp:'コンペ作品',   tone:'#c87648', w:800, h:1000 },
      { id:'o4', t:'Bacon Strips',    jp:'食イラスト',   tone:'#a85838', w:800, h:1000 },
      { id:'o5', t:'Chips Plate',     jp:'食イラスト',   tone:'#d8a868', w:800, h:1000 },
      { id:'o6', t:'Fruit Sundae',    jp:'食イラスト',   tone:'#e8c8b8', w:800, h:1000 },
      { id:'o7', t:'Sandwich Stack',  jp:'食イラスト',   tone:'#d8b888', w:800, h:1000 },
      { id:'o8', t:'Taiyaki',         jp:'食イラスト',   tone:'#c89868', w:800, h:1000 },
      { id:'o9', t:'Sushi Set',       jp:'食イラスト',   tone:'#e8d8c8', w:800, h:1000 },
      { id:'o10',t:'Napolitan',       jp:'食イラスト',   tone:'#d85838', w:800, h:1000 },
      { id:'o11',t:'Quiet Field',     jp:'3DCG',        tone:'#7894a4', w:800, h:1000 },
      { id:'o12',t:'Alien Portrait',  jp:'3DCG',        tone:'#9aa8a8', w:800, h:1000 },
      { id:'o13',t:'Twin Aliens',     jp:'3DCG',        tone:'#88a0a8', w:800, h:1000 },
      { id:'o14',t:'UFO Encounter',   jp:'3DCG',        tone:'#a8b4b8', w:800, h:1000 },
      { id:'o15',t:'UFO at Dusk',     jp:'3DCG',        tone:'#d8c4a8', w:800, h:1000 },
    ],
  },
];

window.PORTFOLIO = PORTFOLIO;
